services:
  redis:
    image: redis

  sso-dashboard:
    build: .
    env_file: envfile
    environment:
      - AWS_DEFAULT_REGION=us-west-2
      - FLASK_DEBUG=True
      - FLASK_APP=dashboard/app.py
    ports:
      - 8000:8000
    volumes:
      - ./dashboard:/dashboard
    entrypoint: "/usr/local/bin/flask"
    command: run --host=0.0.0.0 --port 8000
